### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by r4nchy** [porjo/freshtube#2]
I came across this and it worked few years ago, I am trying it again but it doesn't seem to work. The thumbnails don't seem to showup anymore.

I am wondering if the project is still working ?

and if so then it would be awesome to add the https://dearrow.ajay.app/ into this project as an optional feature.

Thanks

**Comment by porjo** [comment]
I use it almost daily, works fine for me. Maybe try generating a new API key.

**Comment by alx-xlx** [comment]
I tried generating the new api but even the new one doesn't work. How can I debug or see logs ?

**Comment by porjo** [comment]
Ok. Open your browser developer tools (F12 in Firefox and Chrome) and check for any errors in the 'console'. Take a screenshot of you can.

**Comment by alx-xlx** [comment]
![Screenshot 2023-12-01 at 11 42 35 PM](https://github.com/porjo/freshtube/assets/42188371/d48127f9-7a87-4f6b-b023-5f947cd17f9d)

this is what I got

**Comment by porjo** [comment]
The issue is that Freshtube can't deal with Youtube 'handles', only [usernames or channel IDs](https://support.google.com/youtube/answer/6180214?sjid=7675313692240031750-AP).

Replace this:
https://www.youtube.com/@RossmanGroup

With this:
https://www.youtube.com/user/RossmanGroup

I did look at supporting handles originally but can't remember why it didn't work. I'll take another look to see how to support handles.

**Comment by porjo** [comment]
I looked into this again and reminded myself why I couldn't get handles working. fyi, I've created a new ticket with the explanation if you're interested: https://github.com/porjo/freshtube/issues/3 

Unfortunately, there's no easy fix :(

**Comment by alx-xlx** [comment]
ohhh cool that worked. 
 Thanks
